<?xml version="1.0"?>
<robot name="hub" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- <xacro:include filename="$(find hub)/urdf/hub.gazebo.xacro"/> -->
    <xacro:include filename="$(find hub)/urdf/hub_properties.urdf.xacro"/>
		<link name="world"/>

    <!-- base link -->
    <link name="base_link">
        <visual>
					<geometry>
					</geometry>
        </visual>

        <inertial>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
            <mass value="0.1"/>
        </inertial>
    </link>

  	<joint name="world_to_base" type="fixed">
  	  <origin rpy="0 0 0" xyz="0 0 0.9"/>
  	  <parent link="world"/>
  	  <child link="base_link"/>
  	</joint>

    <!-- alumnium extrusion frame macro-->
    <xacro:macro name="frame" params="suffix rotation x_reflect z_reflect length">
        <link name="${suffix}_extrusion">
						<collision>
                <geometry>
                    <box size="${ext_width} ${ext_height} ${length}"/>
                </geometry>
						</collision>
            <visual>
                <material name="grey"/>
                <geometry>
                    <box size="${ext_width} ${ext_height} ${length}"/>
                </geometry>
            </visual>
					  <inertial>
            	<inertia ixx="0.000" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.00"/>
            	<mass value="0.01"/>
        		</inertial>
        </link>

        <joint name="${suffix}_extrusion_to_base" type="fixed">
            <parent link="base_link"/>
            <child link="${suffix}_extrusion"/>
            <origin xyz="${x_reflect*hub_width/2} 0.0 ${z_reflect*hub_height/2}" rpy="0.0 ${rotation} 0.0"/>
        </joint>

    </xacro:macro>

    <!-- create the frame -->
    <xacro:frame suffix= "bottom" rotation="${-1*pi_val/2}" x_reflect="0" z_reflect="-1.0" length="${hub_width+ext_width}"/>
    <xacro:frame suffix="top" rotation="${-1*pi_val/2}" x_reflect="0" z_reflect="1.0" length="${hub_width+ext_width}"/>
    <xacro:frame suffix="left" rotation="0.0" x_reflect="-1.0" z_reflect="0.0" length="${ext_length}"/>
    <xacro:frame suffix="right" rotation="0.0" x_reflect="1.0" z_reflect="0.0" length="${ext_length}"/>


    <!-- x axis arm -->
    <link name="x_axis_arm">
        <visual>
            <material name="black"/>
            <geometry>
                <box size="${ext_width} ${ext_height} ${x_axis_arm_length}"/>
            </geometry>
        </visual>
        <inertial>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.001"/>
            <mass value="2"/>
            <!-- <mass value="${al_density*ext_width*ext_height*x_axis_arm_length}"/> -->
        </inertial>
    </link>

    <joint name="x_axis_arm_joint" type="prismatic">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 ${pi_val/2} 0.0"/>
        <parent link="base_link"/>
        <child link="x_axis_arm"/>
        <axis xyz="1 0 0"/>
         <limit effort="10000" lower="-${hub_height/2}" upper="${hub_height/2}" velocity="1" />
    </joint>

  	<ros2_control name="GazeboSystem" type="system">
  	  <hardware>
  	    <plugin>gazebo_ros2_control/GazeboSystem</plugin>
  	  </hardware>
  	  <joint name="x_axis_arm_joint">
  	    <command_interface name="position">
  	      <param name="min">${-hub_height/2}</param>
  	      <param name="max">${hub_height/2}</param>
  	    </command_interface>
  	    <state_interface name="position"/>
  	    <state_interface name="velocity"/>
  	    <state_interface name="effort"/>
  	  </joint>
  	</ros2_control>

    <!-- parcel holder -->
    <link name="parcel_holder">
        <visual>
            <geometry>
                <!-- TODO: Figure why this mesh file can't be read|found -->
                <!-- <mesh filename="file://$(find hub)/meshes/parcel_holder.obj" scale="1.0 1.0 1.0"/> -->

                <!-- make shift -->
                <box size="${holder_thickness} ${holder_length} ${holder_width}"/>
            </geometry>
        </visual>
        <inertial>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.001"/>
            <mass value="0.5"/>
        </inertial>
    </link>

    <joint name="x_axis_arm_to_holder" type="prismatic">
        <parent link="x_axis_arm"/>
        <child link="parcel_holder"/>
        <origin xyz="-${ext_width} 0.0 0.0"/>
        <axis xyz="0 0 1"/>
        <limit effort="10000" lower="-${hub_width/2}" upper="${hub_width/2}" velocity="0.01" />
    </joint>

  	<ros2_control name="GazeboSystem" type="system">
  	  <hardware>
  	    <plugin>gazebo_ros2_control/GazeboSystem</plugin>
  	  </hardware>
  	  <joint name="x_axis_arm_to_holder">
  	    <command_interface name="position">
  	      <param name="min">${-hub_width/2}</param>
  	      <param name="max">${hub_width/2}></param>
  	    </command_interface>
  	    <state_interface name="position"/>
  	    <state_interface name="velocity"/>
  	    <state_interface name="effort"/>
  	  </joint>
  	</ros2_control>



</robot>
